# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'goruntuisleme.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
from PyQt5.QtWidgets import QFileDialog
from PyQt5.QtGui import QImage
import cv2, imutils


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(690, 695)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.widget = QtWidgets.QWidget(self.centralwidget)
        self.widget.setGeometry(QtCore.QRect(0, 10, 651, 637))
        self.widget.setObjectName("widget")
        self.gridLayout = QtWidgets.QGridLayout(self.widget)
        self.gridLayout.setContentsMargins(0, 0, 0, 0)
        self.gridLayout.setObjectName("gridLayout")
        self.pushButton_3 = QtWidgets.QPushButton(self.widget)
        self.pushButton_3.setObjectName("pushButton_3")
        self.gridLayout.addWidget(self.pushButton_3, 1, 1, 1, 1)
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout.addItem(spacerItem, 1, 2, 1, 1)
        self.pushButton = QtWidgets.QPushButton(self.widget)
        self.pushButton.setObjectName("pushButton")
        self.gridLayout.addWidget(self.pushButton, 1, 0, 1, 1)
        self.label = QtWidgets.QLabel(self.widget)
        self.label.setText("")
        self.label.setPixmap(QtGui.QPixmap("can.jpg"))
        self.label.setObjectName("label")
        self.gridLayout.addWidget(self.label, 0, 0, 1, 2)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 690, 21))
        self.menubar.setObjectName("menubar")
        self.menuFilters = QtWidgets.QMenu(self.menubar)
        self.menuFilters.setObjectName("menuFilters")
        self.menu1 = QtWidgets.QMenu(self.menuFilters)
        self.menu1.setObjectName("menu1")
        self.menuExposure_Histogram = QtWidgets.QMenu(self.menubar)
        self.menuExposure_Histogram.setObjectName("menuExposure_Histogram")
        self.menuConverter = QtWidgets.QMenu(self.menubar)
        self.menuConverter.setObjectName("menuConverter")
        self.menuYo_unluk_D_n_m = QtWidgets.QMenu(self.menubar)
        self.menuYo_unluk_D_n_m.setObjectName("menuYo_unluk_D_n_m")
        self.menuMorfolojik = QtWidgets.QMenu(self.menubar)
        self.menuMorfolojik.setObjectName("menuMorfolojik")
        self.menuVideo_D_zenle = QtWidgets.QMenu(self.menubar)
        self.menuVideo_D_zenle.setObjectName("menuVideo_D_zenle")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.action2 = QtWidgets.QAction(MainWindow)
        self.action2.setObjectName("action2")
        self.action3 = QtWidgets.QAction(MainWindow)
        self.action3.setObjectName("action3")
        self.action4 = QtWidgets.QAction(MainWindow)
        self.action4.setObjectName("action4")
        self.action5 = QtWidgets.QAction(MainWindow)
        self.action5.setObjectName("action5")
        self.action6 = QtWidgets.QAction(MainWindow)
        self.action6.setObjectName("action6")
        self.action7 = QtWidgets.QAction(MainWindow)
        self.action7.setObjectName("action7")
        self.action8 = QtWidgets.QAction(MainWindow)
        self.action8.setObjectName("action8")
        self.action9 = QtWidgets.QAction(MainWindow)
        self.action9.setObjectName("action9")
        self.action10 = QtWidgets.QAction(MainWindow)
        self.action10.setObjectName("action10")
        self.action1_2 = QtWidgets.QAction(MainWindow)
        self.action1_2.setObjectName("action1_2")
        self.action2_2 = QtWidgets.QAction(MainWindow)
        self.action2_2.setObjectName("action2_2")
        self.action3_2 = QtWidgets.QAction(MainWindow)
        self.action3_2.setObjectName("action3_2")
        self.action4_2 = QtWidgets.QAction(MainWindow)
        self.action4_2.setObjectName("action4_2")
        self.action5_2 = QtWidgets.QAction(MainWindow)
        self.action5_2.setObjectName("action5_2")
        self.action1_3 = QtWidgets.QAction(MainWindow)
        self.action1_3.setObjectName("action1_3")
        self.action2_3 = QtWidgets.QAction(MainWindow)
        self.action2_3.setObjectName("action2_3")
        self.action3_3 = QtWidgets.QAction(MainWindow)
        self.action3_3.setObjectName("action3_3")
        self.action4_3 = QtWidgets.QAction(MainWindow)
        self.action4_3.setObjectName("action4_3")
        self.action5_3 = QtWidgets.QAction(MainWindow)
        self.action5_3.setObjectName("action5_3")
        self.action6_2 = QtWidgets.QAction(MainWindow)
        self.action6_2.setObjectName("action6_2")
        self.action7_2 = QtWidgets.QAction(MainWindow)
        self.action7_2.setObjectName("action7_2")
        self.action8_2 = QtWidgets.QAction(MainWindow)
        self.action8_2.setObjectName("action8_2")
        self.action9_2 = QtWidgets.QAction(MainWindow)
        self.action9_2.setObjectName("action9_2")
        self.action10_2 = QtWidgets.QAction(MainWindow)
        self.action10_2.setObjectName("action10_2")
        self.menu1.addSeparator()
        self.menu1.addSeparator()
        self.menuFilters.addAction(self.menu1.menuAction())
        self.menuFilters.addAction(self.action2)
        self.menuFilters.addAction(self.action3)
        self.menuFilters.addAction(self.action4)
        self.menuFilters.addAction(self.action5)
        self.menuFilters.addAction(self.action6)
        self.menuFilters.addAction(self.action7)
        self.menuFilters.addAction(self.action8)
        self.menuFilters.addAction(self.action9)
        self.menuFilters.addAction(self.action10)
        self.menuConverter.addAction(self.action1_2)
        self.menuConverter.addAction(self.action2_2)
        self.menuConverter.addAction(self.action3_2)
        self.menuConverter.addAction(self.action4_2)
        self.menuConverter.addAction(self.action5_2)
        self.menuMorfolojik.addAction(self.action1_3)
        self.menuMorfolojik.addAction(self.action2_3)
        self.menuMorfolojik.addAction(self.action3_3)
        self.menuMorfolojik.addAction(self.action4_3)
        self.menuMorfolojik.addAction(self.action5_3)
        self.menuMorfolojik.addAction(self.action6_2)
        self.menuMorfolojik.addAction(self.action7_2)
        self.menuMorfolojik.addAction(self.action8_2)
        self.menuMorfolojik.addAction(self.action9_2)
        self.menuMorfolojik.addAction(self.action10_2)
        self.menubar.addAction(self.menuFilters.menuAction())
        self.menubar.addAction(self.menuExposure_Histogram.menuAction())
        self.menubar.addAction(self.menuConverter.menuAction())
        self.menubar.addAction(self.menuYo_unluk_D_n_m.menuAction())
        self.menubar.addAction(self.menuMorfolojik.menuAction())
        self.menubar.addAction(self.menuVideo_D_zenle.menuAction())
    
        self.retranslateUi(MainWindow)
        self.pushButton.clicked.connect(self.loadImage)
        self.pushButton_3.clicked.connect(self.savePhoto)
        self.action2.triggered.connect(self.my_roberts)
        self.action3.triggered.connect(self.my_kirsh)
        self.action4.triggered.connect(self.go_original)
        
        QtCore.QMetaObject.connectSlotsByName(MainWindow)
        self.filename = "can.jpg" # Will hold the image address location
        self.tmp = QtGui.QPixmap("can.jpg") # Will hold the temporary image for display
        
        
    
    def loadImage(self):
        self.filename = QFileDialog.getOpenFileName(filter="Image (*.*)")[0]
        self.image = cv2.imread(self.filename)
        self.setPhoto(self.image)
        
    def setPhoto(self,image):
        self.tmp = image
        image = imutils.resize(image,width=640)
        frame = cv2.cvtColor(image, cv2.COLOR_BGR2RGB)
        image = QImage(frame, frame.shape[1],frame.shape[0],frame.strides[0],QImage.Format_RGB888)
        self.label.setPixmap(QtGui.QPixmap.fromImage(image))
        
    
    def savePhoto(self):
        
        
        filename = QFileDialog.getSaveFileName(filter="JPG(*.jpg);;PNG(*.png);;TIFF(*.tiff);;BMP(*.bmp)")[0]
        cv2.imwrite(filename,self.tmp)
        print('Image saved as:',self.filename)
    
    
    def my_roberts(self):
        roberts_image = cv2.imread(self.filename,0)
        temp = roberts_image.copy()

        for i in range(0, roberts_image.shape[0]-1):
            for j in range(0, roberts_image.shape[1]-1):
                A = abs(roberts_image.item(i,j) - roberts_image.item(i+1,j+1))
                B = abs(roberts_image.item(i+1,j) - roberts_image.item(i,j+1))
                temp.itemset((i,j), max(A,B))
        self.setPhoto(temp)
    def go_original(self):
        self.image = cv2.imread(self.filename)
        self.setPhoto(self.image)
    
    
    def my_kirsh(self):
        
        im= cv2.imread(self.filename,0)
        temp = im.copy()
        #print(im.shape[0],im.shape[1])
        for i in range(1,im.shape[0]-1):    
            for j in range(1,im.shape[1]-1):
                A = abs(im.item(i-1,j)+im.item(i,j+1)+im.item(i+1,j-1)-im.item(i+1,j-1)-im.item(i+1,j)-im.item(i,j-1))
                B = abs(im.item(i-1,j-1)+im.item(i,j-1)+im.item(i-1,j)-im.item(i+1,j+1)-im.item(i,j+1)-im.item(i+1,j))
                mag = (A*A + B*B)**(.5)
                temp.itemset((i,j),mag)
        self.setPhoto(temp)

        
     

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.pushButton_3.setText(_translate("MainWindow", "Kaydet"))
        self.pushButton.setText(_translate("MainWindow", "Dosya Aç"))
        self.menuFilters.setTitle(_translate("MainWindow", "Filters"))
        self.menu1.setTitle(_translate("MainWindow", "1"))
        self.menuExposure_Histogram.setTitle(_translate("MainWindow", "Exposure Histogram"))
        self.menuConverter.setTitle(_translate("MainWindow", "Converter"))
        self.menuYo_unluk_D_n_m.setTitle(_translate("MainWindow", "Yoğunluk Dönüşümü"))
        self.menuMorfolojik.setTitle(_translate("MainWindow", "Morfolojik"))
        self.menuVideo_D_zenle.setTitle(_translate("MainWindow", "Video Düzenle"))
        self.action2.setText(_translate("MainWindow", "MY ROBERT"))
        self.action3.setText(_translate("MainWindow", "MY KIRSH"))
        self.action4.setText(_translate("MainWindow", "Get Original Pic"))
        self.action5.setText(_translate("MainWindow", "5"))
        self.action6.setText(_translate("MainWindow", "6"))
        self.action7.setText(_translate("MainWindow", "7"))
        self.action8.setText(_translate("MainWindow", "8"))
        self.action9.setText(_translate("MainWindow", "9"))
        self.action10.setText(_translate("MainWindow", "10"))
        self.action1_2.setText(_translate("MainWindow", "1"))
        self.action2_2.setText(_translate("MainWindow", "2"))
        self.action3_2.setText(_translate("MainWindow", "3"))
        self.action4_2.setText(_translate("MainWindow", "4"))
        self.action5_2.setText(_translate("MainWindow", "5"))
        self.action1_3.setText(_translate("MainWindow", "1"))
        self.action2_3.setText(_translate("MainWindow", "2"))
        self.action3_3.setText(_translate("MainWindow", "3"))
        self.action4_3.setText(_translate("MainWindow", "4"))
        self.action5_3.setText(_translate("MainWindow", "5"))
        self.action6_2.setText(_translate("MainWindow", "6"))
        self.action7_2.setText(_translate("MainWindow", "7"))
        self.action8_2.setText(_translate("MainWindow", "8"))
        self.action9_2.setText(_translate("MainWindow", "9"))
        self.action10_2.setText(_translate("MainWindow", "10"))


import sys

if __name__ == "__main__":
    app = QtWidgets.QApplication(sys.argv)
    ex = Ui_MainWindow()
    w = QtWidgets.QMainWindow()
    ex.setupUi(w)
    w.show()
    sys.exit(app.exec_())
